### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by roman-voropaev** [emory-libraries/eulxml#17]
Hello, Rebecca. 
Is py3 adoption planned?
Currently *pip3 install* gives this:
```
from eulxml.xpath.core import parse, serialize
    File "C:\Users\Roma\AppData\Local\Temp\pip-build-ea1_sm_t\eulxml\eulxml\xpath\core.py", line 125
      except IOError, e:
                    ^
  SyntaxError: invalid syntax
```

**Comment by rlskoeser** [comment]
@roman-voropaev thanks for the question. I'll look into it and see what is involved.

**Comment by rlskoeser** [comment]
Now python 3 compatible in the new 1.0 release thanks to @ellmetha in #19

**Comment by roman-voropaev** [comment]
That's great, I'll switch to P3 in my project 👍
