### ISSUE TITLE
setup.py: Dependency to six is missing

### ISSUE THREAD

**Issue by jenisys** [emory-libraries/eulxml#20]
VERSION: eulxml-1.0.0
CAUSED-BY: .travis.yml

By installing Django (with all its dependencies) first, you no longer know what the dependencies of the project are.

HOW TO REPEAT:
```bash
$ virtualenv .venv
$ source .venv/bin/activate
$ python setup.py install
...
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
...
 File "/.../eulxml/eulxml/xpath/ast.py", line 28, in <module>
    import six
ImportError: No module named six
```

**Comment by rlskoeser** [comment]
@jenisys thanks for reporting this.  I think the problem was actually in the code that generates the ply parse tables on installation; it was relying on six, but that isn't guaranteed to be available at that point.

Should be fixed in the new 1.0.1
