### ISSUE TITLE
eulxml-1.1.2?

### ISSUE THREAD

**Issue by bcail** [emory-libraries/eulxml#30]
On PyPI, I see a release of 1.1.2. However, here on Github, I see 1.1.1 as the latest release, and don't see where 1.1.2 was released. Also, I'm getting an lxml error when I try to run a script that uses eulxml.

**Comment by rlskoeser** [comment]
Drat.  Thanks for catching that, I forgot to push the hotfix updates & tag to github.  It's there now.

If you need help with the lxml issue and think it's eulxml related (or eulxml/lxml version conflict), go ahead and create a new issue with the details.
