### ISSUE TITLE
eulxml 1.1.2 bumps lxml required version to 3.4.0

### ISSUE THREAD

**Issue by bcail** [emory-libraries/eulxml#31]
We use lxml 3.3.3, and it looks like 3.4.0 is where the collect_ids option was added to the lxml parser (http://lxml.de/3.4/changes-3.4.0.html). So, it looks like eulxml 1.1.2 bumps the required version of lxml.

**Comment by rlskoeser** [comment]
Thanks for letting me know - the collect_ids option was added in a pull request and I didn't think to check.  I'll tag a hotfix with a corrected lxml version dependency.

Is upgrading lxml an issue?  i.e., should the collect_ids use be optional, or is it fine to require a newer version of lxml?
